services:

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - pedido-network

  fiap-pedido-receiver:
    image: draraujoo/fiap-pedido-receiver:latest
    container_name: fiap-pedido-receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE_NAME: order-queue
      RABBITMQ_QUEUE_DURABLE: true
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    restart: on-failure
    networks:
      - pedido-network

networks:
  pedido-network:
    name: pedido-network
    driver: bridge

volumes:
    rabbitmq_data:
