services:

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: fiap-pedido-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - pedido-network

  fiap-pedido-receiver:
    build: .
    container_name: fiap-pedido-receiver
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE_NAME: order-queue
      RABBITMQ_QUEUE_DURABLE: true
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    restart: on-failure
    networks:
      - pedido-network

networks:
  pedido-network:
    driver: bridge
