spring:
  application:
    name: fiap-pedido-receiver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE_NAME:order-queue}
    durable: ${RABBITMQ_QUEUE_DURABLE:true}

server:
  port: ${SERVER_PORT:8083}
